language: python
# See available versions at https://docs.travis-ci.com/user/languages/python/
python:
  - '3.6'
#  - '3.7-dev' # rq fails

#before_install:
  #- pip install awscli
  #- scripts/travis_install_apex.sh

install:
  - pip install -r test_requirements.txt
  - pip install coveralls

script: coverage run -m unittest discover -s tests/

after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true
